- project:
    experimental:
      jobs:
        - collectd-ceilometer-plugin-src
        - collectd-ceilometer-plugin-bin
        - collectd-ceilometer-plugin-src-centos-7
        - collectd-ceilometer-plugin-bin-centos-7

- job:
    name: collectd-ceilometer-plugin-bin
    parent: legacy-dsvm-base
    run: playbooks/legacy/dsvm-collectd-ceilometer-plugin-bin/run.yaml
    post-run: playbooks/legacy/dsvm-collectd-ceilometer-plugin-bin/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/collectd-ceilometer-plugin

- job:
    name: collectd-ceilometer-plugin-bin-centos-7
    parent: legacy-dsvm-base
    run: playbooks/legacy/dsvm-collectd-ceilometer-plugin-bin-centos-7/run.yaml
    post-run: playbooks/legacy/dsvm-collectd-ceilometer-plugin-bin-centos-7/post.yaml
    timeout: 7800
    nodeset: legacy-centos-7
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/collectd-ceilometer-plugin

- job:
    name: collectd-ceilometer-plugin-src
    parent: legacy-dsvm-base
    run: playbooks/legacy/dsvm-collectd-ceilometer-plugin-src/run.yaml
    post-run: playbooks/legacy/dsvm-collectd-ceilometer-plugin-src/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/collectd-ceilometer-plugin

- job:
    name: collectd-ceilometer-plugin-src-centos-7
    parent: legacy-dsvm-base
    run: playbooks/legacy/dsvm-collectd-ceilometer-plugin-src-centos-7/run.yaml
    post-run: playbooks/legacy/dsvm-collectd-ceilometer-plugin-src-centos-7/post.yaml
    timeout: 7800
    nodeset: legacy-centos-7
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/collectd-ceilometer-plugin



