#!/bin/bash -xe

export DEVSTACK_GATE_LIBVIRT_TYPE=kvm
export DEVSTACK_GATE_TEMPEST=0
export DEVSTACK_LOCAL_CONFIG=$DEVSTACK_LOCAL_CONFIG'

# Need to prevent devstack from overwriting the gnocchi dir
# Does no harm anywhere else because this is a fresh install
RECLONE=False
GIT_BRANCH["gnocchi"]=stable/3.1

disable_all_services
enable_service key
enable_service mysql
enable_service rabbit
enable_service dstat

COLLECTD_INSTALL=True
COLLECTD_GNOCCHI_VERBOSE=True
COLLECTD_GNOCCHI_ENABLED=True
GNOCCHI_USE_KEYSTONE=True
'
