#!/bin/bash
#
# common functions for collectd ceilometer plugin
# -----------------------------------------------

# start/stop service
#
function start_collectd {
    if [ -e /usr/lib/systemd/system/collectd.service ] || [ -e /etc/init.d/collectd ]; then
        sudo service collectd restart
    fi
}

function stop_collectd {
    if [ -e /usr/lib/systemd/system/collectd.service ] || [ -e /etc/init.d/collectd ]; then
        sudo service collectd stop
    fi
}


function install_requirements {
    if is_ubuntu; then
        echo "Installing pre-resquisites"
        install_package libvirt-bin libvirt-dev python-libvirt
        if [[ "$COLLECTD_INSTALL_TYPE" == "source" ]]; then
            install_package byacc flex bison build-essential automake libgcrypt20 libtool
        fi
    fi
}

function install_service_file {
    # Configure systemd service file
    if [[ `ls -la /sbin/init` =~ "systemd" ]]; then
        local service_file=/etc/systemd/system/collectd.service
        local collectd_binary=$COLLECTD_PREFIX/sbin/collectd
        local collectd_conf_file=$COLLECTD_PREFIX/etc/collectd.conf

        sudo -E cp $COLLECTD_DIR/contrib/systemd.collectd.service $service_file
        sudo sed 's#ExecStart=.*$#ExecStart='"$collectd_binary"' -C '"$collectd_conf_file"'#g' -i $service_file

        sudo chmod +x $service_file
        # Enable collectd
        sudo systemctl enable collectd
    else
        die $LINENO "No support for systemd on this platform.\n
                     To use collectd, build it, configure the service
                     manually, and set COLLECTD_INSTALL=False."
    fi
}

function build_collectd {

    # $PS4 has been defined to call short_source but the function is not
    # available at this stage.
    OPS4=$PS4
    PS4='+'

    git_clone $COLLECTD_REPO $COLLECTD_DIR $COLLECTD_BRANCH
    pushd $COLLECTD_DIR

    build_output=$( ./build.sh )
    echo "Build output: " $build_output

    ./configure --enable-python --enable-debug \
       --enable-logging --enable-syslog \
       --prefix=$COLLECTD_PREFIX/
    make all
    sudo make install
    popd

    # Allow read access to collectd conf file
    sudo chmod +r $COLLECTD_PREFIX/etc/collectd.conf;

    install_service_file
    add_include_dir

    PS4=$OPS4
}

# install collectd
function install_collectd {
    if [[ "$COLLECTD_INSTALL" == True  ]]; then
        if [[ "$COLLECTD_INSTALL_TYPE" == "source" ]]; then
            build_collectd
        else # if install type is binary
            if is_fedora || is_ubuntu; then
                install_package collectd
            else
                die $LINENO "No support for collectd on this platform"
            fi
        fi
    fi
}

# Add the Include block so that conf dir is read
function add_include_dir {
    sudo -E PREFIX=$COLLECTD_PREFIX bash -c 'cat << EOF >> "$PREFIX"/etc/collectd.conf

    <Include "COLLECTD_CONF_DIR">
        Filter "*.conf"
    </Include>
    EOF'

    # Replace the COLLECTD_CONF_DIR placeholder text with the actual conf dir
    sudo sed -i 's|<Include "COLLECTD_CONF_DIR">|<Include "'$COLLECTD_CONF_DIR'">|g' $COLLECTD_PREFIX/etc/collectd.conf

}

# Add conf file for plugin
function adapt_collectd_conf {
    if [ ! -d "$COLLECTD_CONF_DIR" ]; then
        sudo -E mkdir -p "$COLLECTD_CONF_DIR"
    fi

    sudo cp $COLLECTD_CEILOMETER_DIR/etc/collectd.conf.d/collectd-ceilometer-plugin.conf $COLLECTD_CONF_DIR/

    # Configure collectd-ceiloemter-plugin.conf
    sudo sed -i 's|ModulePath.*$|ModulePath "'$COLLECTD_CEILOMETER_DIR'"|g' $COLLECTD_CONF_DIR/collectd-ceilometer-plugin.conf
    sudo sed -i 's|VERBOSE.*$|VERBOSE '$COLLECTD_CEILOMETER_VERBOSE'|g' $COLLECTD_CONF_DIR/collectd-ceilometer-plugin.conf
    sudo sed -i 's|BATCH_SIZE.*$|BATCH_SIZE "'$COLLECTD_BATCH_SIZE'"|g' $COLLECTD_CONF_DIR/collectd-ceilometer-plugin.conf
    sudo sed -i 's|OS_AUTH_URL.*$|OS_AUTH_URL "'$OS_AUTH_URL'"|g' $COLLECTD_CONF_DIR/collectd-ceilometer-plugin.conf
    sudo sed -i 's|CEILOMETER_URL_TYPE.*$|CEILOMETER_URL_TYPE "'$CEILOMETER_URL_TYPE'"|g' $COLLECTD_CONF_DIR/collectd-ceilometer-plugin.conf
    sudo sed -i 's|CEILOMETER_TIMEOUT.*$|CEILOMETER_TIMEOUT "'$CEILOMETER_TIMEOUT'"|g' $COLLECTD_CONF_DIR/collectd-ceilometer-plugin.conf
    sudo sed -i 's|OS_PASSWORD.*$|OS_PASSWORD "'$SERVICE_PASSWORD'"|g' $COLLECTD_CONF_DIR/collectd-ceilometer-plugin.conf
    sudo sed -i 's|OS_TENANT_NAME.*$|OS_TENANT_NAME "'$SERVICE_TENANT_NAME'"|g' $COLLECTD_CONF_DIR/collectd-ceilometer-plugin.conf

    # Configure custom units
    if [[ "$COLLECTD_CEILOMETER_UNITS" != none ]]; then
        OIFS=$IFS
        IFS=','
        for UNIT in $COLLECTD_CEILOMETER_UNITS
        do
            sudo sed -i '/<UNITS>/a\       UNIT '"$UNIT"'' $COLLECTD_CONF_DIR/collectd-ceilometer-plugin.conf
        done
        IFS=$OIFS
    fi

    # Configure collectd logfile plugin
    if [ -n $COLLECTD_LOG_FILE ]; then
        touch $COLLECTD_LOG_FILE
    fi

    sudo cp $COLLECTD_CEILOMETER_DIR/etc/collectd.conf.d/logfile.conf $COLLECTD_CONF_DIR/

    sudo sed -i 's|LogLevel.*$|LogLevel "'$COLLECTD_LOG_LEVEL'"|g' $COLLECTD_CONF_DIR/logfile.conf
    sudo sed -i 's|File.*$|File "'$COLLECTD_LOG_FILE'"|g' $COLLECTD_CONF_DIR/logfile.conf

}


# remove plugin conf file
function restore_collectd_conf {

    if [ -f '$COLLECTD_CONF_DIR/collectd-ceilometer-plugin.conf' ]; then
        sudo rm -f $COLLECTD_CONF_DIR/collectd-ceilometer-plugin.conf
        sudo rm -f $COLLECTD_CONF_DIR/logfile.conf
    fi

}
